// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Labb_2_databaser.Migrations
{
    [DbContext(typeof(BokhandelContext))]
    partial class BokhandelContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Labb_2_databaser.Models2.Butiker", b =>
                {
                    b.Property<int>("ButikId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ButikId"));

                    b.Property<string>("Adress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Butiksnamn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Land")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Postnummer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Stad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefon")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ButikId");

                    b.ToTable("Butiker", (string)null);
                });

            modelBuilder.Entity("Labb_2_databaser.Models2.Böcker", b =>
                {
                    b.Property<string>("ISBN13")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("AntalSidor")
                        .HasColumnType("int");

                    b.Property<int?>("FörfattareId")
                        .HasColumnType("int");

                    b.Property<string>("Förlag")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Genre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Pris")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Språk")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Titel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("Utgivningsdatum")
                        .HasColumnType("date");

                    b.HasKey("ISBN13");

                    b.ToTable("Böcker");
                });

            modelBuilder.Entity("Labb_2_databaser.Models2.Kunder", b =>
                {
                    b.Property<int>("KundId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KundId"));

                    b.Property<string>("Adress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Efternamn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Epost")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Förnamn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Land")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Stad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefon")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("KundId");

                    b.ToTable("Kunder");
                });

            modelBuilder.Entity("Labb_2_databaser.Models2.Lagersaldo", b =>
                {
                    b.Property<int>("ButikId")
                        .HasColumnType("int");

                    b.Property<int>("Antal")
                        .HasColumnType("int");

                    b.Property<string>("Isbn")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ButikId");

                    b.HasIndex("Isbn");

                    b.ToTable("Lagersaldo");
                });

            modelBuilder.Entity("Labb_2_databaser.Models2.Ordrar", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"));

                    b.Property<int?>("KundId")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("OrderDatum")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("TotaltPris")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("OrderId");

                    b.HasIndex("KundId");

                    b.ToTable("Ordrar");
                });

            modelBuilder.Entity("Labb_2_databaser.Models2.Recensioner", b =>
                {
                    b.Property<int>("RecensionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RecensionId"));

                    b.Property<int?>("Betyg")
                        .HasColumnType("int");

                    b.Property<string>("Boktitel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Isbn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IsbnNavigationISBN13")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("KundId")
                        .HasColumnType("int");

                    b.Property<string>("RecensionText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("Recensionsdatum")
                        .HasColumnType("date");

                    b.HasKey("RecensionId");

                    b.HasIndex("IsbnNavigationISBN13");

                    b.HasIndex("KundId");

                    b.ToTable("Recensioner");
                });

            modelBuilder.Entity("Labb_2_databaser.Models2.Lagersaldo", b =>
                {
                    b.HasOne("Labb_2_databaser.Models2.Butiker", "Butiker")
                        .WithMany("Lagersaldo")
                        .HasForeignKey("ButikId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Labb_2_databaser.Models2.Böcker", "Böcker")
                        .WithMany("Lagersaldo")
                        .HasForeignKey("Isbn")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Butiker");

                    b.Navigation("Böcker");
                });

            modelBuilder.Entity("Labb_2_databaser.Models2.Ordrar", b =>
                {
                    b.HasOne("Labb_2_databaser.Models2.Kunder", "Kund")
                        .WithMany("Ordrars")
                        .HasForeignKey("KundId");

                    b.Navigation("Kund");
                });

            modelBuilder.Entity("Labb_2_databaser.Models2.Recensioner", b =>
                {
                    b.HasOne("Labb_2_databaser.Models2.Böcker", "IsbnNavigation")
                        .WithMany("Recensioners")
                        .HasForeignKey("IsbnNavigationISBN13");

                    b.HasOne("Labb_2_databaser.Models2.Kunder", "Kund")
                        .WithMany("Recensioners")
                        .HasForeignKey("KundId");

                    b.Navigation("IsbnNavigation");

                    b.Navigation("Kund");
                });

            modelBuilder.Entity("Labb_2_databaser.Models2.Butiker", b =>
                {
                    b.Navigation("Lagersaldo");
                });

            modelBuilder.Entity("Labb_2_databaser.Models2.Böcker", b =>
                {
                    b.Navigation("Lagersaldo");

                    b.Navigation("Recensioners");
                });

            modelBuilder.Entity("Labb_2_databaser.Models2.Kunder", b =>
                {
                    b.Navigation("Ordrars");

                    b.Navigation("Recensioners");
                });
#pragma warning restore 612, 618
        }
    }
}
